/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.org.igen;

import br.org.igen.netbeans.plugin.maven.MavenProject;
import br.org.igen.netbeans.plugin.maven.MavenProjects;
import br.org.igen.netbeans.plugin.maven.PomPackagingType;
import br.org.igen.netbeans.plugin.server.ApplicationServer;
import br.org.igen.netbeans.plugin.server.SupportedApplicationServer;
import br.org.igen.netbeans.plugin.settings.Settings;
import br.org.igen.netbeans.plugin.settings.PropertiesFileSettingsStore;
import java.io.File;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import org.openide.util.Lookup;

/**
 *
 * @author gabrielhof
 */
public class ProjectSettingPanel extends javax.swing.JPanel {

    private Lookup lookup;
    
    private List<SupportedApplicationServer> supportedApplicationServers;
    private List<MavenProject> earModules;

    private Settings settings;
    
    private JFileChooser fileChooser = new JFileChooser();
    
    /**
     * Creates new form ProjectSettingPanel
     */
    public ProjectSettingPanel(Lookup lookup) {
        this.lookup = lookup;
        
        loadData();
        initComponents();
        configureComponents();
    }

    private void loadData() {
        this.supportedApplicationServers = SupportedApplicationServer.all();
        
        this.earModules = MavenProjects.getDefault().getOpenedProjects()
                .stream().filter(m -> m.getPomInfo().isPackaging(PomPackagingType.EAR))
                .collect(Collectors.toList());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelDefaultModule = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboEarModules = new javax.swing.JComboBox<>();
        checkboxActivate = new javax.swing.JCheckBox();
        panelEarModule = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldApplicationServerDirectory = new javax.swing.JTextField();
        botaoSelecionarArquivo = new javax.swing.JButton();
        comboApplicationServers = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ProjectSettingPanel.class, "ProjectSettingPanel.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ProjectSettingPanel.class, "ProjectSettingPanel.jLabel1.text")); // NOI18N

        jLabel2.setLabelFor(comboEarModules);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(ProjectSettingPanel.class, "ProjectSettingPanel.jLabel2.text")); // NOI18N

        comboEarModules.setModel(new DefaultComboBoxModel<MavenProject>(earModules.toArray(new MavenProject[] {})));
        comboEarModules.setSelectedIndex(-1);
        comboEarModules.setSelectedItem(earModules.isEmpty() ? null : earModules.get(0));

        org.openide.awt.Mnemonics.setLocalizedText(checkboxActivate, org.openide.util.NbBundle.getMessage(ProjectSettingPanel.class, "ProjectSettingPanel.checkboxActivate.text")); // NOI18N
        checkboxActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActivateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDefaultModuleLayout = new javax.swing.GroupLayout(panelDefaultModule);
        panelDefaultModule.setLayout(panelDefaultModuleLayout);
        panelDefaultModuleLayout.setHorizontalGroup(
            panelDefaultModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDefaultModuleLayout.createSequentialGroup()
                .addGroup(panelDefaultModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDefaultModuleLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboEarModules, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkboxActivate, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDefaultModuleLayout.setVerticalGroup(
            panelDefaultModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDefaultModuleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkboxActivate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(panelDefaultModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboEarModules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        checkboxActivate.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(ProjectSettingPanel.class, "ProjectSettingPanel.checkboxActivate.AccessibleContext.accessibleName")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(ProjectSettingPanel.class, "ProjectSettingPanel.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(ProjectSettingPanel.class, "ProjectSettingPanel.jLabel4.text")); // NOI18N

        textFieldApplicationServerDirectory.setText(org.openide.util.NbBundle.getMessage(ProjectSettingPanel.class, "ProjectSettingPanel.textFieldApplicationServerDirectory.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(botaoSelecionarArquivo, org.openide.util.NbBundle.getMessage(ProjectSettingPanel.class, "ProjectSettingPanel.botaoSelecionarArquivo.text")); // NOI18N
        botaoSelecionarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSelecionarArquivoActionPerformed(evt);
            }
        });

        comboApplicationServers.setModel(new DefaultComboBoxModel<ApplicationServer>(supportedApplicationServers.toArray(new ApplicationServer[] {})));

        javax.swing.GroupLayout panelEarModuleLayout = new javax.swing.GroupLayout(panelEarModule);
        panelEarModule.setLayout(panelEarModuleLayout);
        panelEarModuleLayout.setHorizontalGroup(
            panelEarModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEarModuleLayout.createSequentialGroup()
                .addGroup(panelEarModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEarModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEarModuleLayout.createSequentialGroup()
                        .addComponent(textFieldApplicationServerDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSelecionarArquivo))
                    .addComponent(comboApplicationServers, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        panelEarModuleLayout.setVerticalGroup(
            panelEarModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEarModuleLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(panelEarModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboApplicationServers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEarModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldApplicationServerDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSelecionarArquivo))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(panelEarModule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDefaultModule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDefaultModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelEarModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void configureComponents() {
        updateCurrentSettings();
    }
    
    public void updateCurrentSettings() {
        settings = PropertiesFileSettingsStore.getInstance().getSettingsFor(getProject());
        
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setMultiSelectionEnabled(false);
        
        checkboxActivate.setSelected(settings.isActive());
        comboEarModules.setSelectedItem(settings.getEarProject());
        comboApplicationServers.setSelectedItem(settings.getServer());
        
        File serverDiretoryFile = settings.getServerDirectoryAsFile();
        textFieldApplicationServerDirectory.setText(serverDiretoryFile == null ? "" : serverDiretoryFile.toString());
        
        configurePanels();
        updateComboEarModules();
    }
    
    private void configurePanels() {
        boolean isEar = getProject().getPomInfo().isPackaging(PomPackagingType.EAR);
        
        panelEarModule.setVisible(isEar);
        panelDefaultModule.setVisible(!isEar);
    }
    
    private void checkboxActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActivateActionPerformed
        updateComboEarModules();
    }//GEN-LAST:event_checkboxActivateActionPerformed

    private void botaoSelecionarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSelecionarArquivoActionPerformed
        fileChooser.showDialog(this, "Selecionar Pasta");
        
        File file = fileChooser.getSelectedFile();
        textFieldApplicationServerDirectory.setText(file == null ? "" : file.toString());
    }//GEN-LAST:event_botaoSelecionarArquivoActionPerformed

    private void updateComboEarModules() {
        boolean isActive = checkboxActivate.isSelected();
        comboEarModules.setEnabled(isActive);
        
        if (isActive) {
            comboEarModules.setSelectedIndex(0);
        } else {
            comboEarModules.setSelectedItem(null);
        }
    }
    
    public MavenProject getProject() {
        return MavenProjects.getDefault().getCurrent();
    }
    
    public Settings getSettings() {
        settings.setActive(checkboxActivate.isSelected());
        
        MavenProject earProject = (MavenProject) comboEarModules.getSelectedItem();
        
        if (earProject != null) {
            settings.setEarProjectDirectory(earProject.getProjectDirectory());
        } else {
            settings.setEarProjectDirectory((File) null);
        }
        
        settings.setServer(((SupportedApplicationServer) comboApplicationServers.getSelectedItem()));
        
        String serverDirectory = textFieldApplicationServerDirectory.getText();
        
        if (serverDirectory != null && !serverDirectory.isEmpty()) {
            settings.setServerDirectory(new File(serverDirectory));
        } else {
            settings.setServerDirectory((File) null);
        }
        
        return settings;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSelecionarArquivo;
    private javax.swing.JCheckBox checkboxActivate;
    private javax.swing.JComboBox<ApplicationServer> comboApplicationServers;
    private javax.swing.JComboBox<MavenProject> comboEarModules;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelDefaultModule;
    private javax.swing.JPanel panelEarModule;
    private javax.swing.JTextField textFieldApplicationServerDirectory;
    // End of variables declaration//GEN-END:variables
}
